  name: GitHub JAVA CI
  on: [push]
  jobs:
    Build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
        - uses: gradle/gradle-build-action@v3
          with:
            gradle-version: 8.9

        - run:  ./app/gradlew build
        - run: 	./app/gradlew checkstyleMain
        - run: 	./app/gradlew checkstyleTest
        - run: 	./app/gradlew test
        - run: 	./app/gradlew build
